### ISSUE TITLE
Gene page doesn't come up on SCXA

### ISSUE THREAD

**Issue by pcm32** [ebi-gene-expression-group/atlas-web-core#41]
Go to:

https://wwwdev.ebi.ac.uk/gxa/sc/experiments/E-ENAD-15/results/tsne?geneId=ENSMUSG00000041301

Press the Gene information button:

![image](https://user-images.githubusercontent.com/368478/76107134-0fbb7080-5fd0-11ea-930a-38662297fec7.png)

The gene view page doesn't come up:

![image](https://user-images.githubusercontent.com/368478/76107237-28c42180-5fd0-11ea-9675-873e26d4a604.png)

I thought that the issue was with core, but maybe is with SCXA module...

**Comment by alfonsomunozpomer** [comment]
[We got this one covered](https://www.pivotaltracker.com/story/show/171702527), thanks for reporting.
