### ISSUE TITLE
Icons missing for downloads tab in SCXA

### ISSUE THREAD

**Issue by pcm32** [ebi-gene-expression-group/atlas-web-core#42]
When you click on downloads and get to places like:

https://wwwdev.ebi.ac.uk/gxa/sc/experiments/E-MTAB-7142/downloads

icons for downloads seem missing:

![image](https://user-images.githubusercontent.com/368478/76108269-2c58a800-5fd2-11ea-8fa6-589f893de32c.png)

**Comment by alfonsomunozpomer** [comment]
This has now been fixed in https://github.com/ebi-gene-expression-group/atlas-web-single-cell/pull/86.
